### ISSUE TITLE
Schedules should not be generated if customization level is Section and no sections are selected

### ISSUE THREAD

**Issue by firejake308** [aggie-coding-club/Rev-Registration#286]
Currently, if you set the customization level to Section, then Generate Schedules without selecting any sections, it generates schedules. This feels counter-intuitive, since we have given the algorithm an empty list of sections to choose from, and theoretically, this should result in no options.

Even if this was intentional, in that the default state should allow all options, this would be more clearly indicated by having all sections start off as checked. Either way, setting customization level to Section and sending an empty list of sections should logically result in no schedules generated for that course.

**Comment by firejake308** [comment]
Wait, I just realized this might be due to #283, so we should fix that first

**Comment by ryan-conn** [comment]
This is intentional, I explicitly checked if sections is empty before filtering the section query during schedule generation (see `_get_meetings()` in `create_schedules.py`).

I agree it might be a little unintuitive, but I don't think selecting them all is a great solution since in most situations, the user will only want to select a one or a few sections instead of unchecking a bunch of them, so imo a select all button would be a better way to implement this.

If we do decide to make it so selecting no sections results in no schedules being generated, we should also add an error message to the course card so that the user is aware of the fact that this will mess up schedule generation.

Another point to consider regardless of what we end up doing is that "all sections" includes honors/online classes that most users won't want to include, I think a good solution for this is to add the basic filter options to the section select as well and disable checkboxes for sections that don't pass the user's filter requirements

**Comment by ryan-conn** [comment]
Closed after discussion, we might reopen this later but for now the current behavior seems preferable
