### ISSUE TITLE
Extend LAST_HOUR by 1 hour

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#370]
Both CSCE 121 and MATH 151 have tests that go till 10:30 PM (those bastards), so we should extend it by 30 minutes as our current limit is 10:00 PM

**Comment by firejake308** [comment]
It'll probably be easier to just bump last hour up to 11

**Comment by firejake308** [comment]
Also, when I increased last hour from 9 to 10, I think I had to update some tests manually, so heads up for whoever this gets assigned to

**Comment by gannonprudhomme** [comment]
that works for me

**Comment by gannonprudhomme** [comment]
I think we should honestly consider making it dynamic somehow (assuming it doesn't feel weird). KINE-199 (section 461 for Fall 2020 CS) has 7 AM courses, but I don't think we should completely shift it since I feel like 95% of courses aren't allowed to start before 8 AM.

**Comment by ryan-conn** [comment]
If we made it dynamic, we'd have to somehow let users create availability blocks in the parts of the calendar that aren't shown by default, and I can't really think of a way to let them do that without being really clunky. We definitely have to think more about the best solution to this

**Comment by ryan-conn** [comment]
Also at least for the mini-schedules, a good solution imo would be to just use `overflow: hidden` on the availability blocks, since a block at the end makes it pretty clear that you'll have a really late class in that schedule, and the point of the mini schedules is conveying information quickly rather than super accurately
