### ISSUE TITLE
Change references of "web" to "remote"

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#395]
Given that we're adding `asynchronous` usage to the website, we should change any instances of our site of `web` to `remote` just to be more precise. I could be convinced to to leave it with web (or even change it to online), but given the rise of asynchronous classes I think it's worth being precise

**Comment by ryan-conn** [comment]
Hello @joneskj55, while I love your interest in contributing, we recently found a few new contributors for this project and would like to assign them these kinds of issues. Since this project is for the coding club at A&M, we have a lot of discussion and weekly meetings outside of GitHub, and unfortunately we're not currently looking for new contributors.

If you don't mind letting us know, I'm curious how you found this repo, since we haven't really posted anything about it publicly but have noticed quite a few people have viewed it in the past few days. I'm sorry that we're not really in a position right now to add more contributors given the number of people that just joined this project, but I hope you can find other repos to contribute to— your GitHub profile looks very nice, and if we didn't just get 5 new members we would have loved to have you contribute.

**Comment by joneskj55** [comment]
Hi @ryan-conn no worries! I stumbled upon your repo by doing an issue search. I think I may have added label:good-first-issue to the search. You're probably getting a lot of viewers since its Hacktoberfest and everyone's looking for ways to contribute and get four valid pull requests in October. Thanks for getting back to me.
