### ISSUE TITLE
Fix site.webmanifest CORS error on GCP Storage

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#436]
I have to do some configuring with GCP storage to make it so that site.webmanifest or w/e allows cross-origin requests. This shouldn't need to be a change committed in the codebase or anything.

**Comment by ThatJuanGuy** [comment]
https://medium.com/@jbrojbrojbro/google-cloud-storage-and-cors-2-2-91f56af88351

**Comment by ThatJuanGuy** [comment]
This is supposed to be a JSON file though instead of a .txt but file type was not supported.
I think this is what the settings should be but I'm not exactly sure on responseHeader. I kinda just took all the response headers from the requests I could find on the site and put them there.
[corsJSON.txt](https://github.com/aggie-coding-club/Rev-Registration/files/5745624/corsJSON.txt)
