### ISSUE TITLE
Use gzip for main.js

### ISSUE THREAD

**Issue by ryan-conn** [aggie-coding-club/Rev-Registration#440]
Google app engine is supposed to automatically use gzip for html, css, and js when the appropriate headers are set, for example:
![image](https://user-images.githubusercontent.com/28655462/97480085-f2e9f980-1920-11eb-817d-72958e57b954.png)
![image](https://user-images.githubusercontent.com/28655462/97480124-009f7f00-1921-11eb-8f15-2798d4952c7e.png)

However, the one file I noticed it doesn't do this with is `main.js`, which is unfortunate as it's by far our biggest file. It would be nice to have it use gzip as well:
![image](https://user-images.githubusercontent.com/28655462/97480375-4f4d1900-1921-11eb-8888-5bc7baa6cb83.png)

I'm not sure if the problem lays with app engine or with django, we'll have to look more into how static files are being handled on deployment.

**Comment by gannonprudhomme** [comment]
It's a problem with Google Storage since that's where are static files are located - from a few seconds of research it seems we can put `Content-Encoding: gzip` on the `main.js` file. However, the `main.js` file would have to be gzipped before hand - otherwise it won't actually apply (from what I can tell). Got this from Google Storage documentation [here](https://cloud.google.com/storage/docs/transcoding#content-type_vs_content-encoding)
