### ISSUE TITLE
Implement Babel

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#52]
We need to implement babel in order to reduce our bundle size for production going forward.

While we won't see a benefit from this now, it'll be good to have set up going forward.

Also, look at [minimizing bundle size](https://material-ui.com/guides/minimizing-bundle-size/#minimizing-bundle-size) for Material-UI

**Comment by firejake308** [comment]
<img width="960" alt="2019-11-23" src="https://user-images.githubusercontent.com/10082177/69489942-985d3900-0e45-11ea-86e9-b11f35b93345.png">
I ran webpack-bundle-analyzer, and currently, 72% of our build is Material-UI. When reducing our build size, our first priority should be minimizing this library. At the extreme end, considering the fact that I custom-CSS'ed the schedule, it's not unreasonable to suggest dumping the library entirely. It will lead to lots of custom CSS, and consequently, lots of pain, but it would also cut our build size in half. Furthermore, let's be real: at the moment, 275 KiB of code is coloring the background of the app bar and giving us a home icon. That could be accomplished much more succinctly.

**Comment by gannonprudhomme** [comment]
> At the extreme end, considering the fact that I custom-CSS'ed the schedule, it's not unreasonable to suggest dumping the library entirely

Before we consider dumping it entirely, we should try to [reduce the bundle size](https://material-ui.com/guides/minimizing-bundle-size/).

**Comment by ryan-conn** [comment]
Adding to what Gannon said, using babel should reduce the bundle size substantially. Right now, we have to import all of `material-ui/core` and `material-ui/styles` to use just a few components, which is (presumably) why it takes up so much space. I'm going to try to get babel working in the next couple days and see how much space it needs then.

**Comment by ryan-conn** [comment]
Trying to use babel now, I realized that webpack is already doing the thing we're trying to use babel for (tree shaking), and even after that, material-ui is still using 300kb. While I agree the file size is a bit excessive, we're using material-ui for more now than just the background/home icon: the navbar, all typography, the term select, and cards (for meeting cards and the text on the home page) all currently rely on material-ui, and while we could remove it, I think it's probably worth it to keep, especially for things like switches, text fields, and buttons that we can use rather than making our own.

On a related note, this leaves me wondering why we should set up babel anymore: initially it was for reducing bundle size, but as I said, now that we're using webpack, it does that for us. Considering we won't need it for anything that I can think of, we can probably just not use it.

**Comment by gannonprudhomme** [comment]
Pretty sure we don't need, so closing this
