### ISSUE TITLE
generating schedule for removed courses

### ISSUE THREAD

**Issue by AnnySuho** [aggie-coding-club/Rev-Registration#555]
![image](https://user-images.githubusercontent.com/51311762/116453643-be4df080-a824-11eb-9f9b-1c41e187a514.png)
313 and 465 are still being generated even after it was removed from the add course column. refreshing doesn't help etc.

edit: i do not have a guess for what is actually causing this though. i was quite excited to have this become my goto source but this issue i think is somewhat critical and i cant really depend on it if it gives me bugged schedules. forces me to cross check with the disgusting native howdy one :(

**Comment by firejake308** [comment]
Hello and thank you for filing the issue. I'm pretty sure the reason that 313 didn't get removed is because you currently have Schedule 1 saved/locked. Saved/locked schedules won't be affected by adding/removing courses, so that you can compare different schedules with different classes. If you no longer wish to include 313 in any of your schedules, deleting the saved Schedule 1 and re-generating schedules should solve your issue. If not, please let us know and we will look into it further

**Comment by AnnySuho** [comment]
great that fixed it; i must have accidentally clicked it sometime when play testing. maybe add some sort of intro thing for these explaining functionality like how initially the graphic schedule had instructions had to block off time?

**Comment by gannonprudhomme** [comment]
Yeah something like that certainly isn't the users (your) fault - was clear that you didn't notice it, and as such that part of the website doesn't seem to be as intuitive as we would like. Thanks for filling this (and the many other) issues, stuff like this really helps us improve the site! We'll be discussing this next time we meet :)

**Comment by AnnySuho** [comment]
honestly i really like this product and hope to see it become even better. keep up the good work!
