### ISSUE TITLE
Increase size of course select column

### ISSUE THREAD

**Issue by gannonprudhomme** [aggie-coding-club/Rev-Registration#568]
Probably the most frequent suggestion we've been getting is that the course select column doesn't use enough space. As such, we should shrink the space the schedule gets and increase the space the course select column gets (since it's the most important part, after all)

From a bit of preliminary testing we released that around ~750px for max-width of the schedule probably is good, but we could even go as low as 550px (from what I can tell).

**Comment by firejake308** [comment]
How does this relate to #566?

**Comment by gannonprudhomme** [comment]
It doesn't necessarily - I think #566 is more so for people who want to like screenshot their schedule (which we should implement a feature for btw) and is a state change (e.g. click a "full screen" button on the schedule), while this is more so changing the default look of the website by giving the course select column more space by default (or rather, giving it a higher `flex-grow` priority than the schedule and the schedule-preview column).

**Comment by gannonprudhomme** [comment]
Mind picking this up @firejake308 ? Should hopefully be straightforward, advanced flex scares me though

**Comment by firejake308** [comment]
Yessir

**Comment by firejake308** [comment]
Here's what I got so far. I added `max-width` to the schedule and the middle column as well

|1440p| 4K|
|--|--|
|![localhost_8000_schedule (2)](https://user-images.githubusercontent.com/10082177/117065074-9a8b1e80-acec-11eb-9c71-d033b3964f26.png)|![localhost_8000_schedule (1)](https://user-images.githubusercontent.com/10082177/117065092-9fe86900-acec-11eb-9f81-4917ada40c77.png)|

**Comment by gannonprudhomme** [comment]
Did you mean like 720p for the left one? Surely that's not 1440p

But for the 4K one, that was basically the problem I was running into - at a certain point the schedule should be able to expand (course column is way too big imo), but I guess really only once the course select column + middle column have enough space? Idk if we'd have to add programmatic stuff for it (guess media queries also might work)

**Comment by firejake308** [comment]
Yeah, I think that of the three columns, the calendar is the one that doesn't look awful when stretched to infinity. So I'm thinking that overall, our priority will be to give more space to the course select column first (since it's so cramped), and once that's legible, any leftover space can be given to the calendar

**Comment by gannonprudhomme** [comment]
> Yeah, I think that of the three columns, the calendar is the one that doesn't look awful when stretched to infinity. So I'm thinking that overall, our priority will be to give more space to the course select column first (since it's so cramped), and once that's legible, any leftover space can be given to the calendar

Agreed

**Comment by firejake308** [comment]
Here is the next iteration.

### My screen:
![image](https://user-images.githubusercontent.com/10082177/117085438-5f4e1700-ad0f-11eb-84f7-493070279a3d.png)

### 4K:
![localhost_8000_schedule (3)](https://user-images.githubusercontent.com/10082177/117085479-83a9f380-ad0f-11eb-8d01-211b5525fc90.png)|

The columns are split 2:1:2, with maxima applied to the left 2 columns so that the calendar can grow indefinitely on large screens. Personally, I don't think I like having all the extra space in the course cards when course titles are getting cut off on the calendar

**Comment by gannonprudhomme** [comment]
> Personally, I don't think I like having all the extra space in the course cards when course titles are getting cut off on the calendar

I do agree that it shouldn't cut off the text for the meetings on the schedule, _however_ we do need to remember that most of the time people are going to be looking at the course cards rather than the schedule (likewise we plan on doing #556 at some point, but I still want it to be legible). Likewise the site does still function like this - the meeting types are more so a bonus (for the most part).

I feel like we need to determine a set of specs/quick designs (probs be easier to manually change widths of columns) of how we want it to look on various screens, e.g. never cut off course text in meeting on schedules (unless absolutely necessary) like you mentioned, etc. The only generalization I can think of (which isn't much of a spec/design lol) is that for the most part, the course cards should be 25% wider than currently, and it should (mostly) take that width from the schedule, and only from the mini schedules if absolutely necessary, as squished mini schedule previews are awful. 

For 4K it looks like the schedule is taking up more space than it does now (it's split down the middle) which I don't think is ideal (frankly I think the current functionality for 4K/1440p is fine, so if it's possible to maintain I would prefer to, but smaller than 1440p is def the priority)

Next iteration can you post a screenshot of what the site looks like now as a reference? Wasn't sure if the mini schedule previews are that small all the time. Likewise include 1080p (way more important than 4K/1440p) please, as that's what a majority of our users use (basically > 25%)

Also just wanted to note that after this change, we'll need to update the media query width that determines when meetings go from one line to two, as it should be able to do one line for your screen there.

sorry this was a lot lol

**Comment by firejake308** [comment]
Posting latest screenshots below. This effectively changes nothing on 1080p and above. On 720p, it takes space from the right 2 columns and gives them to the left column so that it can at least show everyhting on one line. I think the main issue is deciding how to prioritize space between the SchedulePreview and the Schedule itself. Right now, they are splitting the space in a 1:2 ratio. I think what we have right now is acceptable, although it's worth pointing out that professors are getting cut off in SchedulePreview and meeting types are getting cut off in the Schedule

## 720p
![localhost_8000_schedule (4)](https://user-images.githubusercontent.com/10082177/117899874-b0b95180-b28d-11eb-84d2-d8eb52241872.png)

## 1080p
![localhost_8000_schedule (5)](https://user-images.githubusercontent.com/10082177/117899884-b57e0580-b28d-11eb-8c13-87910373f841.png)

## 1440p
![localhost_8000_schedule (6)](https://user-images.githubusercontent.com/10082177/117899901-c0d13100-b28d-11eb-95dc-92c4123c4d5e.png)
